export const API_PREFIX = "/api/v1";

export const apiEndpoints = {
  analytics: {
    abTest: (testId: string) => `/analytics/ab-tests/${testId}`,
    abTestResults: (testId: string) => `/analytics/ab-tests/${testId}/results`,
    abTests: "/analytics/ab-tests",
    churnRisk: "/analytics/churn-risk",
    churnRiskUser: (userId: string) => `/analytics/churn-risk/${userId}`,
    ltv: "/analytics/ltv",
    ltvUser: (userId: string) => `/analytics/ltv/${userId}`,
    retrainMl: "/analytics/ml/retrain",
    exports: "/analytics/exports",
    reports: "/analytics/reports",
    scheduledReports: "/analytics/scheduled-reports",
    whatIf: "/analytics/what-if",
  },
  auth: {
    confirm2faSetup: "/auth/2fa/confirm",
    disable2fa: "/auth/2fa",
    login: "/auth/login",
    logout: "/auth/logout",
    me: "/auth/me",
    refresh: "/auth/refresh",
    setup2fa: "/auth/2fa/setup",
    verify2fa: "/auth/2fa/verify",
  },
  automations: {
    automation: (automationId: string) => `/automations/${automationId}`,
    automationRun: (automationId: string) => `/automations/${automationId}/run`,
    automationToggle: (automationId: string) => `/automations/${automationId}/toggle`,
    list: "/automations",
    runActive: "/automations/run-active",
  },
  billing: {
    gateway: (gatewayId: string) => `/payment-gateways/${gatewayId}`,
    gatewayTest: (gatewayId: string) => `/payment-gateways/${gatewayId}/test`,
    gateways: "/payment-gateways",
    report: "/billing/report",
    reportExport: "/billing/report/export",
    transaction: (transactionId: string) => `/transactions/${transactionId}`,
    transactionRefund: (transactionId: string) => `/transactions/${transactionId}/refund`,
    transactions: "/transactions",
  },
  dashboard: {
    anomalies: "/dashboard/anomalies",
    kpis: "/dashboard/kpis",
    mrrChart: "/dashboard/mrr-chart",
    newUsers: "/dashboard/new-users",
    riskSummary: "/dashboard/risk-summary",
    topServices: "/dashboard/top-services",
  },
  gamification: {
    achievement: (achievementId: string) => `/achievements/${achievementId}`,
    achievements: "/achievements",
    loyaltyLedger: "/loyalty/ledger",
    loyaltyPointsAdjust: "/loyalty/points/adjust",
    loyaltySummary: "/loyalty/summary",
    loyaltyTier: (tierId: string) => `/loyalty/tiers/${tierId}`,
    loyaltyTiers: "/loyalty/tiers",
    review: (reviewId: string) => `/reviews/${reviewId}`,
    reviewReply: (reviewId: string) => `/reviews/${reviewId}/reply`,
    reviews: "/reviews",
    reward: (rewardId: string) => `/rewards/${rewardId}`,
    rewardHistory: "/rewards/history",
    rewards: "/rewards",
  },
  health: {
    health: "/health",
    metrics: "/metrics",
  },
  jobs: {
    list: "/jobs",
    job: (jobId: string) => `/jobs/${jobId}`,
  },
  marketing: {
    campaign: (campaignId: string) => `/campaigns/${campaignId}`,
    campaignCancel: (campaignId: string) => `/campaigns/${campaignId}/cancel`,
    campaignSend: (campaignId: string) => `/campaigns/${campaignId}/send`,
    campaigns: "/campaigns",
    promoCode: (promoId: string) => `/promo-codes/${promoId}`,
    promoCodes: "/promo-codes",
    promoCodesBulk: "/promo-codes/bulk",
    referralConfig: "/referrals/config",
    referralStats: "/referrals/stats",
    referrals: "/referrals",
    segment: (segmentId: string) => `/segments/${segmentId}`,
    segmentRefresh: (segmentId: string) => `/segments/${segmentId}/refresh`,
    segments: "/segments",
    template: (templateId: string) => `/templates/${templateId}`,
    templates: "/templates",
  },
  mobile: {
    achievements: "/mobile/achievements",
    applyPromo: "/mobile/subscriptions/apply-promo",
    authLogin: "/mobile/auth/login",
    authLogout: "/mobile/auth/logout",
    authRefresh: "/mobile/auth/refresh",
    authRegister: "/mobile/auth/register",
    catalog: "/mobile/catalog",
    points: "/mobile/points",
    profile: "/mobile/profile",
    services: "/mobile/services",
    subscriptions: "/mobile/subscriptions",
  },
  notifications: {
    list: "/notifications",
    notification: (notificationId: string) => `/notifications/${notificationId}`,
  },
  security: {
    adminUser: (adminId: string) => `/admin-users/${adminId}`,
    adminUsers: "/admin-users",
    auditLog: "/audit-log",
    auditLogExport: "/audit-log/export",
    session: (jti: string) => `/sessions/${jti}`,
    sessions: "/sessions",
    settings: "/settings",
    policies: "/security/policies",
  },
  stream: {
    anomalies: "/stream/anomalies",
    notifications: "/stream/notifications",
  },
  subscriptions: {
    subscriptionApplyPromo: (subscriptionId: string) => `/subscriptions/${subscriptionId}/apply-promo`,
    subscription: (subscriptionId: string) => `/subscriptions/${subscriptionId}`,
    subscriptions: "/subscriptions",
    tariff: (tariffId: string) => `/tariffs/${tariffId}`,
    tariffArchive: (tariffId: string) => `/tariffs/${tariffId}/archive`,
    tariffDuplicate: (tariffId: string) => `/tariffs/${tariffId}/duplicate`,
    tariffSubscribers: (tariffId: string) => `/tariffs/${tariffId}/subscribers`,
    tariffs: "/tariffs",
  },
  users: {
    achievements: (userId: string) => `/users/${userId}/achievements`,
    activity: (userId: string) => `/users/${userId}/activity`,
    block: (userId: string) => `/users/${userId}/block`,
    bulkAction: "/users/bulk-action",
    deductPoints: (userId: string) => `/users/${userId}/deduct-points`,
    export: "/users/export",
    grantPoints: (userId: string) => `/users/${userId}/grant-points`,
    list: "/users",
    notes: (userId: string) => `/users/${userId}/notes`,
    subscriptions: (userId: string) => `/users/${userId}/subscriptions`,
    transactions: (userId: string) => `/users/${userId}/transactions`,
    unblock: (userId: string) => `/users/${userId}/unblock`,
    user: (userId: string) => `/users/${userId}`,
  },
} as const;

export function apiPath(path: string): string {
  return `${API_PREFIX}${path}`;
}
