import type {
  AnalyticsWorkspace,
  Anomaly,
  DashboardKpis,
  GamificationWorkspace,
  MarketingWorkspace,
  MrrPoint,
  SecurityWorkspace,
  SettingsWorkspace,
  SmartAnalyticsWorkspace,
  Tariff,
  TopService,
  UserProfile,
} from "./contracts";

export const dashboardKpis: DashboardKpis = {
  active_users: {
    delta_pct: 12.4,
    trend: "up",
    value: 48392,
  },
  churn_rate: {
    delta_pp: 0.4,
    is_alert: true,
    trend: "up",
    value: 0.032,
  },
  ltv_cac_ratio: {
    romi_pct: 280,
    trend: "up",
    value: 3.8,
  },
  mrr: {
    arr: 101000000,
    currency: "RUB",
    delta_pct: 8.7,
    trend: "up",
    value: 8420000,
  },
  updated_at: "2026-06-05T00:00:00.000Z",
};

export const mrrChart: MrrPoint[] = [
  { date: "2026-04-20", mrr: 6900000, new_users: 286 },
  { date: "2026-04-27", mrr: 7180000, new_users: 314 },
  { date: "2026-05-04", mrr: 7060000, new_users: 361 },
  { date: "2026-05-11", mrr: 7520000, new_users: 392 },
  { date: "2026-05-18", mrr: 8420000, new_users: 412 },
];

export const anomalies: Anomaly[] = [
  {
    created_at: "2026-05-19T07:15:00.000Z",
    description:
      "За последние 24 часа отток превысил скользящее среднее. Проверьте платежные ошибки и отмены пробных периодов.",
    id: "anom_churn_24h",
    is_read: false,
    severity: "critical",
    title: "Рост churn на 23%",
  },
  {
    created_at: "2026-05-19T06:40:00.000Z",
    description:
      "Robokassa показывает рост неуспешных платежей. Рекомендуется переключить приоритет на резервный шлюз.",
    id: "anom_decline_rate",
    is_read: false,
    severity: "warning",
    title: "Decline rate 6.8%",
  },
  {
    created_at: "2026-05-18T18:05:00.000Z",
    description:
      "Партнер МТС отвечает медленнее нормы, средняя задержка за период составила 480 мс.",
    id: "anom_partner_latency",
    is_read: true,
    severity: "info",
    title: "API latency p95 вырос",
  },
];

const services = {
  kinopoisk: {
    icon_url: "/services/kinopoisk.svg",
    id: "svc_kinopoisk",
    name: "Кинопоиск",
  },
  mts: {
    icon_url: "/services/mts.svg",
    id: "svc_mts",
    name: "МТС Premium",
  },
  netflix: {
    icon_url: "/services/netflix.svg",
    id: "svc_netflix",
    name: "Netflix",
  },
  spotify: {
    icon_url: "/services/spotify.svg",
    id: "svc_spotify",
    name: "Spotify",
  },
  yandex: {
    icon_url: "/services/yandex.svg",
    id: "svc_yandex",
    name: "Яндекс Плюс",
  },
};

export const topServices: TopService[] = [
  { ...services.spotify, subscribers: 12480 },
  { ...services.yandex, name: "YouTube Premium", subscribers: 10230 },
  { ...services.netflix, subscribers: 8125 },
  { ...services.kinopoisk, name: "Я.Музыка", subscribers: 6890 },
  { ...services.mts, name: "FitnessApp", subscribers: 3412 },
];

export const tariffs: Tariff[] = [
  {
    currency: "RUB",
    id: "tariff_plus",
    is_public: true,
    name: "Plus",
    period: "month",
    price: 399,
    services: [services.yandex, services.kinopoisk],
    status: "active",
    subscribers: 8420,
    trial_days: 14,
  },
  {
    currency: "RUB",
    id: "tariff_family",
    is_public: true,
    name: "Family",
    period: "month",
    price: 699,
    services: [services.yandex, services.kinopoisk, services.spotify],
    status: "active",
    subscribers: 5160,
    trial_days: 7,
  },
  {
    currency: "RUB",
    id: "tariff_ultimate",
    is_public: true,
    name: "Ultimate",
    period: "month",
    price: 1190,
    services: [
      services.yandex,
      services.kinopoisk,
      services.spotify,
      services.netflix,
      services.mts,
    ],
    status: "active",
    subscribers: 2840,
    trial_days: 0,
  },
  {
    currency: "RUB",
    id: "tariff_legacy_2025",
    is_public: false,
    name: "Legacy 2025",
    period: "year",
    price: 4990,
    services: [services.yandex, services.kinopoisk],
    status: "archived",
    subscribers: 310,
    trial_days: 0,
  },
];

export const marketingWorkspace: MarketingWorkspace = {
  automation_rules: [
    {
      channel: "push",
      delay_hours: 2,
      id: "auto-001",
      name: "Продление D-3",
      segment: "Истекают через 3 дня",
      status: "active",
      template_id: "tpl-001",
      trigger: "subscription_expires_soon",
    },
    {
      channel: "sms",
      delay_hours: 1,
      id: "auto-002",
      name: "Повтор платежа",
      segment: "Платеж отклонен",
      status: "paused",
      template_id: "tpl-002",
      trigger: "payment_failed",
    },
  ],
  campaigns: [
    {
      audience_size: 128420,
      channel: "push",
      conversion_rate: 8.4,
      ctr: 8.4,
      id: "cmp-001",
      name: "Продление D-3",
      segment: "Истекают через 3 дня",
      starts_at: "2026-05-27T09:00:00.000Z",
      status: "scheduled",
    },
    {
      audience_size: 42100,
      channel: "email",
      conversion_rate: 5.8,
      ctr: 5.8,
      id: "cmp-002",
      name: "Возврат 14 дней",
      segment: "Спящие 14 дней",
      starts_at: "2026-05-29T11:00:00.000Z",
      status: "draft",
    },
    {
      audience_size: 18300,
      channel: "sms",
      conversion_rate: 3.1,
      ctr: 3.1,
      id: "cmp-003",
      name: "Повтор платежа",
      segment: "Платеж отклонен",
      starts_at: "2026-05-21T08:30:00.000Z",
      status: "completed",
    },
    {
      audience_size: 67800,
      channel: "email",
      conversion_rate: 9.2,
      ctr: 12.6,
      id: "cmp-004",
      name: "Годовой Family",
      segment: "Family без годового тарифа",
      starts_at: "2026-06-01T10:00:00.000Z",
      status: "sending",
    },
  ],
  experiments: [
    {
      audience_size: 42000,
      channel: "push",
      hypothesis: "Короткий оффер повысит конверсию продления.",
      id: "exp-001",
      name: "Продление D-3: короткий оффер",
      segment: "Истекают через 3 дня",
      starts_at: "2026-05-27T09:00:00.000Z",
      status: "running",
      variants: [
        {
          audience_pct: 50,
          conversion_rate: 8.1,
          ctr: 11.4,
          key: "A",
          title: "Скидка 10% на год",
        },
        {
          audience_pct: 50,
          conversion_rate: 9.3,
          ctr: 12.8,
          key: "B",
          title: "Сохраните подписки без перерыва",
        },
      ],
      winner: null,
    },
    {
      audience_size: 18300,
      channel: "sms",
      hypothesis: "Упоминание способа оплаты снизит потерю платежей.",
      id: "exp-002",
      name: "Повтор платежа: CTA",
      segment: "Платеж отклонен",
      starts_at: "2026-05-21T08:30:00.000Z",
      status: "completed",
      variants: [
        {
          audience_pct: 50,
          conversion_rate: 3.1,
          ctr: 4.7,
          key: "A",
          title: "Повторить платеж",
        },
        {
          audience_pct: 50,
          conversion_rate: 4.4,
          ctr: 5.9,
          key: "B",
          title: "Обновить карту и повторить",
        },
      ],
      winner: "B",
    },
  ],
  message_drafts: [
    {
      body: "Ваша подписка скоро закончится. Продлите доступ без перерыва.",
      channel: "push",
      cta: "Продлить",
      id: "msg-001",
      name: "Push продление D-3",
      scheduled_at: "2026-05-27T09:00:00.000Z",
      segment: "Истекают через 3 дня",
      status: "scheduled",
      title: "Подписка заканчивается",
    },
    {
      body: "Платеж не прошел. Обновите карту, чтобы подписка осталась активной.",
      channel: "sms",
      cta: "Обновить карту",
      id: "msg-002",
      name: "SMS повтор платежа",
      scheduled_at: "2026-05-24T12:00:00.000Z",
      segment: "Платеж отклонен",
      status: "draft",
      title: "Нужна оплата",
    },
  ],
  promo_coupons: [
    {
      code: "FRIEND500",
      discount_type: "fixed",
      discount_value: 500,
      expires_at: "2026-06-30T23:59:59.000Z",
      id: "coupon-001",
      segment: "Новые по рефералам",
      status: "active",
      title: "Бонус другу",
      usage_limit: 5000,
      used_count: 1840,
    },
    {
      code: "FAMILY20",
      discount_type: "percent",
      discount_value: 20,
      expires_at: "2026-07-15T23:59:59.000Z",
      id: "coupon-002",
      segment: "Family без годового тарифа",
      status: "scheduled",
      title: "Family лето",
      usage_limit: 2500,
      used_count: 0,
    },
    {
      code: "RETURN15",
      discount_type: "percent",
      discount_value: 15,
      expires_at: "2026-05-31T23:59:59.000Z",
      id: "coupon-003",
      segment: "Спящие 14 дней",
      status: "active",
      title: "Возврат подписки",
      usage_limit: 1200,
      used_count: 312,
    },
  ],
  referral_events: [
    {
      advocate: "Анна Морозова",
      channel: "push",
      friend: "Олег Волков",
      id: "ref-001",
      invited_at: "2026-05-24T09:30:00.000Z",
      reward: "500 баллов",
      status: "rewarded",
    },
    {
      advocate: "Илья Соколов",
      channel: "sms",
      friend: "Мария Климова",
      id: "ref-002",
      invited_at: "2026-05-23T14:20:00.000Z",
      reward: "Скидка 15%",
      status: "active",
    },
    {
      advocate: "Мария Кузнецова",
      channel: "email",
      friend: "Дмитрий Орлов",
      id: "ref-003",
      invited_at: "2026-05-22T11:10:00.000Z",
      reward: "300 баллов",
      status: "pending",
    },
  ],
  referral_summary: {
    active_advocates: 8420,
    conversion_rate: 18.7,
    conversions_month: 2180,
    invites_month: 11640,
    reward_budget: 1460000,
  },
  referral_tiers: [
    {
      advocate_reward: "300 баллов",
      friend_reward: "10% на первый месяц",
      id: "ref-tier-001",
      invite_goal: 1,
      name: "Первое приглашение",
      status: "active",
    },
    {
      advocate_reward: "500 баллов",
      friend_reward: "500 RUB скидка",
      id: "ref-tier-002",
      invite_goal: 3,
      name: "Активный амбассадор",
      status: "active",
    },
    {
      advocate_reward: "Premium 30 дней",
      friend_reward: "20% на Family",
      id: "ref-tier-003",
      invite_goal: 10,
      name: "Лидер рекомендаций",
      status: "paused",
    },
  ],
  segments: [
    {
      audience_size: 18420,
      filters: { churn_risk: "high", status: "active" },
      id: "segment-001",
      name: "Высокий риск оттока",
      updated_at: "2026-05-24T08:00:00.000Z",
    },
    {
      audience_size: 42100,
      filters: { tariff: "Premium", status: "active" },
      id: "segment-002",
      name: "Premium активные",
      updated_at: "2026-05-24T08:30:00.000Z",
    },
    {
      audience_size: 8900,
      filters: { status: "trial" },
      id: "segment-003",
      name: "Триал пользователи",
      updated_at: "2026-05-24T09:00:00.000Z",
    },
  ],
  templates: [
    {
      body: "Ваша подписка скоро закончится. Продлите доступ без перерыва.",
      category: "Продление",
      channel: "push",
      cta: "Продлить",
      id: "tpl-001",
      name: "Продление подписки",
      status: "active",
      subject: "Подписка заканчивается",
      usage_count: 18,
    },
    {
      body: "Платеж не прошел. Обновите карту, чтобы подписка осталась активной.",
      category: "Платежи",
      channel: "sms",
      cta: "Обновить карту",
      id: "tpl-002",
      name: "Повтор платежа",
      status: "active",
      subject: "Нужна оплата",
      usage_count: 11,
    },
    {
      body: "Мы подготовили подборку сервисов для вашего тарифа.",
      category: "Активация",
      channel: "push",
      cta: "Открыть",
      id: "tpl-003",
      name: "Открытие сервисов",
      status: "draft",
      subject: "Новые сервисы ждут",
      usage_count: 3,
    },
  ],
};

export const analyticsWorkspace: AnalyticsWorkspace = {
  cohorts: [
    {
      arpu: "RUB 860",
      churn: "3.8%",
      id: "cohort-001",
      name: "Мартовская когорта",
      recommendation: "Усилить видимость годового оффера",
      retention: "71%",
      users: 18420,
    },
    {
      arpu: "RUB 710",
      churn: "4.9%",
      id: "cohort-002",
      name: "Апрельская когорта",
      recommendation: "Добавить push-напоминание о продлении на D-3",
      retention: "64%",
      users: 22180,
    },
    {
      arpu: "RUB 620",
      churn: "6.2%",
      id: "cohort-003",
      name: "Пробный период",
      recommendation: "Проверить экран оплаты после онбординга",
      retention: "52%",
      users: 9400,
    },
  ],
  custom_dashboards: [
    {
      id: "dash-001",
      name: "Дашборд выручки",
      owner: "Финансы",
      period: "30 дней",
      template: "revenue",
      updated_at: "2026-05-24T08:30:00.000Z",
      widgets: [
        {
          id: "widget-001",
          metric: "MRR",
          title: "Месячная выручка",
          trend: "+8.4%",
          value: "RUB 12.8M",
        },
        {
          id: "widget-002",
          metric: "ARPU",
          title: "Средний доход",
          trend: "+3.1%",
          value: "RUB 742",
        },
      ],
    },
    {
      id: "dash-002",
      name: "Дашборд удержания",
      owner: "Аналитика",
      period: "90 дней",
      template: "retention",
      updated_at: "2026-05-23T12:15:00.000Z",
      widgets: [
        {
          id: "widget-003",
          metric: "Удержание",
          title: "Удержание",
          trend: "+2.0 п.п.",
          value: "71%",
        },
        {
          id: "widget-004",
          metric: "Отток",
          title: "Отток",
          trend: "-0.6 п.п.",
          value: "4.1%",
        },
      ],
    },
  ],
  exports: [
    {
      format: "XLSX",
      id: "export-001",
      name: "MRR по тарифам",
      rows: "18,420",
      status: "Готов",
    },
    {
      format: "CSV",
      id: "export-002",
      name: "Когорты оттока",
      rows: "9,400",
      status: "В очереди",
    },
    {
      format: "PDF",
      id: "export-003",
      name: "Сводка удержания",
      rows: "3",
      status: "Готов",
    },
  ],
  reports: [
    {
      arpu: "RUB 742",
      churn: "4.1%",
      id: "rep-001",
      mrr: "RUB 12.8M",
      name: "MRR по тарифам",
      owner: "Финансы",
      period: "30 дней",
      segment: "Все пользователи",
      status: "ready",
    },
    {
      arpu: "RUB 910",
      churn: "3.4%",
      id: "rep-002",
      mrr: "RUB 6.1M",
      name: "Удержание - Premium",
      owner: "Аналитика",
      period: "90 дней",
      segment: "Premium",
      status: "review",
    },
    {
      arpu: "RUB 680",
      churn: "5.2%",
      id: "rep-003",
      mrr: "RUB 3.9M",
      name: "Сервисы - Family",
      owner: "Продукт",
      period: "Год",
      segment: "Family",
      status: "queued",
    },
  ],
  scheduled_reports: [
    {
      format: "PDF",
      frequency: "weekly",
      id: "schedule-001",
      name: "Еженедельная сводка удержания",
      next_run_at: "2026-05-25T09:00:00.000Z",
      owner_email: "analytics@subhub.local",
      status: "Активно",
    },
    {
      format: "XLSX",
      frequency: "monthly",
      id: "schedule-002",
      name: "Месячный отчет по MRR",
      next_run_at: "2026-06-01T08:00:00.000Z",
      owner_email: "finance@subhub.local",
      status: "Активно",
    },
  ],
  summary: {
    churn: "4.1%",
    churn_delta: "-0.6 п.п. за 30 дней",
    mrr: "RUB 12.8M",
    mrr_delta: "+8.4% к прошлому периоду",
  },
};

export const gamificationWorkspace: GamificationWorkspace = {
  achievements: [
    {
      description: "Первый успешный платеж в мобильном приложении.",
      icon: "CARD",
      id: "ach-001",
      reward_type: "points",
      reward_value: "50",
      status: "active",
      title: "Первый платеж",
      trigger_count: 1,
      trigger_event: "payment_success",
    },
    {
      description: "Семь активных сессий приложения подряд.",
      icon: "STREAK",
      id: "ach-002",
      reward_type: "badge",
      reward_value: "Серия",
      status: "active",
      title: "Серия входов",
      trigger_count: 7,
      trigger_event: "daily_open",
    },
  ],
  loyalty_events: [
    {
      amount: 250,
      date: "24 мая",
      event_type: "earned",
      id: "loyalty-event-001",
      reason: "Продление Premium",
      source: "Подписка",
      user: "Анна Морозова",
    },
    {
      amount: -1200,
      date: "23 мая",
      event_type: "redeemed",
      id: "loyalty-event-002",
      reason: "Premium 30 дней",
      source: "Магазин наград",
      user: "Илья Соколов",
    },
    {
      amount: 100,
      date: "22 мая",
      event_type: "adjusted",
      id: "loyalty-event-003",
      reason: "Компенсация поддержки",
      source: "Админ",
      user: "Мария Кузнецова",
    },
  ],
  loyalty_summary: {
    active_members: 18420,
    average_points_per_user: 428,
    points_balance: 7883760,
    points_earned_month: 842500,
    points_spent_month: 318200,
  },
  loyalty_tiers: [
    {
      benefit: "Базовые начисления за платежи",
      id: "tier-001",
      members: 12240,
      name: "Старт",
      status: "active",
      threshold: 0,
    },
    {
      benefit: "+10% к начислениям и ранний доступ к промо",
      id: "tier-002",
      members: 4820,
      name: "Плюс",
      status: "active",
      threshold: 1000,
    },
    {
      benefit: "+20% к начислениям и премиальные награды",
      id: "tier-003",
      members: 1360,
      name: "Премиум",
      status: "active",
      threshold: 3000,
    },
  ],
  rewards: [
    {
      category: "Доступ",
      cost: 1200,
      id: "reward-001",
      name: "Premium 30 дней",
      redemptions: 184,
      stock: 24,
    },
    {
      category: "Скидка",
      cost: 500,
      id: "reward-002",
      name: "Скидка 15%",
      redemptions: 420,
      stock: 900,
    },
    {
      category: "Мерч",
      cost: 2400,
      id: "reward-003",
      name: "Худи SubHub",
      redemptions: 32,
      stock: 8,
    },
  ],
  reviews: [
    {
      date: "21 мая",
      id: "rev-001",
      rating: 2,
      response: "",
      sentiment: "negative",
      source: "App Store",
      status: "new",
      tags: ["платеж", "поддержка"],
      text: "Платеж не прошел, и подписка не продлилась.",
      user: "Анна Р.",
    },
    {
      date: "20 мая",
      id: "rev-002",
      rating: 5,
      response: "Спасибо за отзыв.",
      sentiment: "positive",
      source: "Google Play",
      status: "resolved",
      tags: ["контент"],
      text: "Удобно отслеживать подписки.",
      user: "Илья К.",
    },
    {
      date: "19 мая",
      id: "rev-003",
      rating: 4,
      response: "",
      sentiment: "neutral",
      source: "Telegram",
      status: "progress",
      tags: ["онбординг"],
      text: "Нужно понятнее объяснить, как работают баллы.",
      user: "Мария С.",
    },
  ],
};

export const smartAnalyticsWorkspace: SmartAnalyticsWorkspace = {
  automations: [
    {
      audience: "820 пользователей",
      channel: "Push + Email",
      id: "automation-001",
      name: "Автоматизация возврата",
      status: "review",
      trigger: "risk_score > 0.8",
    },
    {
      audience: "410 пользователей",
      channel: "Push",
      id: "automation-002",
      name: "Повтор платежа",
      status: "active",
      trigger: "платёж не прошёл",
    },
    {
      audience: "1 260 пользователей",
      channel: "In-app",
      id: "automation-003",
      name: "Подбор сервисов",
      status: "draft",
      trigger: "список подписок пуст",
    },
  ],
  risk_segments: [
    {
      churn_probability_pct: 82,
      confidence_pct: 91,
      expected_loss: 1400000,
      id: "risk-001",
      name: "Premium без годового плана",
      owner: "CRM",
      recommended_action: "предложить годовую скидку",
      risk_score: 0.82,
      top_drivers: ["ежемесячное продление", "чувствительность к цене", "нет годовой скидки"],
      users: 820,
    },
    {
      churn_probability_pct: 76,
      confidence_pct: 88,
      expected_loss: 740000,
      id: "risk-002",
      name: "Платёж отклонён дважды",
      owner: "Поддержка",
      recommended_action: "запустить повтор платежа",
      risk_score: 0.76,
      top_drivers: ["отклонённые платежи", "карта истекла", "открыто обращение в поддержку"],
      users: 410,
    },
    {
      churn_probability_pct: 68,
      confidence_pct: 84,
      expected_loss: 520000,
      id: "risk-003",
      name: "Подписки не добавлены",
      owner: "Продукт",
      recommended_action: "показать подбор сервисов",
      risk_score: 0.68,
      top_drivers: ["пустой список подписок", "низкая активация", "онбординг пропущен"],
      users: 1260,
    },
  ],
  scenarios: [
    {
      churn_delta_pp: 0.4,
      horizon_months: 3,
      id: "scenario-001",
      ltv_impact_pct: 7.8,
      name: "Premium +8%",
      price_delta_pct: 8,
      projected_mrr: 13900000,
      status: "ready",
      tariff: "Premium",
    },
    {
      churn_delta_pp: 0.2,
      horizon_months: 6,
      id: "scenario-002",
      ltv_impact_pct: 4.1,
      name: "Family +5%",
      price_delta_pct: 5,
      projected_mrr: 5200000,
      status: "review",
      tariff: "Family",
    },
    {
      churn_delta_pp: -0.5,
      horizon_months: 1,
      id: "scenario-003",
      ltv_impact_pct: 2.4,
      name: "Trial onboarding",
      price_delta_pct: 0,
      projected_mrr: 1100000,
      status: "draft",
      tariff: "Trial",
    },
  ],
};

export const securityWorkspace: SecurityWorkspace = {
  access_rules: [
    {
      expires: "Постоянно",
      id: "access-001",
      owner: "Безопасность",
      permission: "billing.read",
      role: "Финансовый менеджер",
      scope: "Платежи",
      status: "active",
    },
    {
      expires: "7 дней",
      id: "access-002",
      owner: "Администратор",
      permission: "users.block",
      role: "Лид поддержки",
      scope: "Пользователи",
      status: "review",
    },
    {
      expires: "Истек",
      id: "access-003",
      owner: "Безопасность",
      permission: "reports.export",
      role: "Аналитик",
      scope: "Аналитика",
      status: "expired",
    },
  ],
  audit_events: [
    {
      action: "RBAC обновлен",
      actor: "Елена Админ",
      evidence: "role_matrix_v4",
      id: "audit-001",
      ip: "185.12.44.18",
      severity: "medium",
      target: "Лид поддержки",
      time: "13:10",
    },
    {
      action: "Подозрительная сессия закрыта",
      actor: "Система",
      evidence: "ip_velocity_check",
      id: "audit-002",
      ip: "91.219.32.10",
      severity: "high",
      target: "Администратор поддержки",
      time: "11:42",
    },
    {
      action: "2FA включена",
      actor: "Иван Поддержка",
      evidence: "totp_setup",
      id: "audit-003",
      ip: "10.0.0.42",
      severity: "low",
      target: "Иван Поддержка",
      time: "Вчера",
    },
  ],
  change_history: [
    {
      audit_event_id: "audit-001",
      author: "Елена Админ",
      created_at: "13:12",
      description: "Проверена матрица ролей и подтвержден доступ лида поддержки.",
      id: "history-001",
    },
    {
      audit_event_id: "audit-002",
      author: "Система",
      created_at: "11:44",
      description: "Сессия закрыта после проверки скорости смены IP.",
      id: "history-002",
    },
    {
      audit_event_id: "audit-003",
      author: "Иван Поддержка",
      created_at: "Вчера",
      description: "Пользователь завершил настройку TOTP и подтвердил резервные коды.",
      id: "history-003",
    },
  ],
  mfa_coverage_pct: 96,
  mfa_policy: {
    backup_codes_required: 8,
    grace_period_days: 7,
    min_coverage_pct: 95,
    required_for_roles: ["owner", "security", "finance"],
    updated_at: "2026-05-24T12:20:00.000Z",
  },
  mfa_users: [
    {
      admin: "Елена Админ",
      backup_codes_left: 8,
      id: "mfa-001",
      last_challenge_at: "12 минут назад",
      primary_factor: "webauthn",
      recommendation: "Оставить аппаратный ключ как основной фактор.",
      risk: "low",
      role: "owner",
      status: "enabled",
      trusted_devices: 2,
    },
    {
      admin: "Иван Поддержка",
      backup_codes_left: 4,
      id: "mfa-002",
      last_challenge_at: "Вчера",
      primary_factor: "totp",
      recommendation: "Обновить резервные коды после следующего входа.",
      risk: "medium",
      role: "support",
      status: "pending",
      trusted_devices: 1,
    },
    {
      admin: "Финансовый менеджер",
      backup_codes_left: 0,
      id: "mfa-003",
      last_challenge_at: "Не проходил",
      primary_factor: "sms",
      recommendation: "Обязать настройку TOTP до доступа к платежам.",
      risk: "high",
      role: "finance",
      status: "disabled",
      trusted_devices: 0,
    },
  ],
  rate_limit_rules: [
    {
      burst: 20,
      endpoint: "/api/auth/*",
      id: "rate-001",
      limit: 60,
      name: "Авторизация",
      owner: "Безопасность",
      risk: "high",
      status: "active",
      updated_at: "12:30",
      window_seconds: 60,
    },
    {
      burst: 80,
      endpoint: "/api/users/*",
      id: "rate-002",
      limit: 240,
      name: "Пользователи",
      owner: "Поддержка",
      risk: "medium",
      status: "review",
      updated_at: "Вчера",
      window_seconds: 60,
    },
    {
      burst: 10,
      endpoint: "/api/analytics/export",
      id: "rate-003",
      limit: 30,
      name: "Экспорт отчётов",
      owner: "Аналитика",
      risk: "medium",
      status: "active",
      updated_at: "10:15",
      window_seconds: 300,
    },
  ],
  header_policies: [
    {
      coverage_pct: 96,
      header: "Content-Security-Policy",
      id: "header-001",
      recommendation: "Добавить report-uri для staging и production окружений.",
      risk: "medium",
      status: "review",
      value: "default-src 'self'; frame-ancestors 'none'",
    },
    {
      coverage_pct: 100,
      header: "Strict-Transport-Security",
      id: "header-002",
      recommendation: "Политика включена для всех HTTPS ответов.",
      risk: "low",
      status: "active",
      value: "max-age=31536000; includeSubDomains",
    },
    {
      coverage_pct: 92,
      header: "X-Frame-Options",
      id: "header-003",
      recommendation: "Проверить старые admin preview маршруты.",
      risk: "medium",
      status: "review",
      value: "DENY",
    },
  ],
  permission_matrix: [
    {
      analyst: true,
      area: "Отчеты",
      finance: true,
      id: "perm-001",
      owner: true,
      security: true,
      support: false,
    },
    {
      analyst: false,
      area: "Пользователи",
      finance: false,
      id: "perm-002",
      owner: true,
      security: true,
      support: true,
    },
    {
      analyst: false,
      area: "Платежи",
      finance: true,
      id: "perm-003",
      owner: true,
      security: false,
      support: false,
    },
    {
      analyst: false,
      area: "Политики безопасности",
      finance: false,
      id: "perm-004",
      owner: true,
      security: true,
      support: false,
    },
  ],
  role_assignments: [
    {
      changed_by: "Елена Админ",
      id: "assign-001",
      reason: "Финансовая сверка",
      role: "finance",
      status: "active",
      user: "Мария Финансы",
    },
    {
      changed_by: "Елена Админ",
      id: "assign-002",
      reason: "Разбор обращений",
      role: "support",
      status: "review",
      user: "Иван Поддержка",
    },
  ],
  roles: [
    {
      description: "Полный доступ к консоли и критичным настройкам.",
      id: "owner",
      name: "Владелец",
      risk: "high",
      users: 2,
    },
    {
      description: "Управляет RBAC, аудитом и активными сессиями.",
      id: "security",
      name: "Безопасность",
      risk: "medium",
      users: 3,
    },
    {
      description: "Работает с пользователями и обращениями поддержки.",
      id: "support",
      name: "Поддержка",
      risk: "medium",
      users: 8,
    },
    {
      description: "Просматривает платежи, счета и финансовые отчеты.",
      id: "finance",
      name: "Финансы",
      risk: "low",
      users: 5,
    },
    {
      description: "Просматривает отчеты и экспорт аналитики.",
      id: "analyst",
      name: "Аналитик",
      risk: "low",
      users: 6,
    },
  ],
  sessions: [
    {
      admin: "Администратор поддержки",
      device: "iPhone 15 Pro",
      id: "session-001",
      ip: "91.219.32.10",
      last_seen: "2 минуты назад",
      location: "Берлин, DE",
      risk: "high",
      status: "active",
    },
    {
      admin: "Елена Админ",
      device: "MacBook Pro",
      id: "session-002",
      ip: "185.12.44.18",
      last_seen: "12 минут назад",
      location: "Москва, RU",
      risk: "low",
      status: "active",
    },
    {
      admin: "Финансовый менеджер",
      device: "Windows Desktop",
      id: "session-003",
      ip: "10.0.0.44",
      last_seen: "1 час назад",
      location: "Офисный VPN",
      risk: "medium",
      status: "active",
    },
  ],
  session_history: [
    {
      action: "Сессия отмечена как рискованная",
      actor: "Система",
      created_at: "11:40",
      id: "session-history-001",
      reason: "Обнаружена быстрая смена IP и новая страна входа.",
      session_id: "session-001",
    },
    {
      action: "Проверка владельца устройства",
      actor: "Елена Админ",
      created_at: "12:18",
      id: "session-history-002",
      reason: "Устройство подтверждено через внутренний канал поддержки.",
      session_id: "session-002",
    },
    {
      action: "VPN-сессия проверена",
      actor: "Финансовая безопасность",
      created_at: "12:55",
      id: "session-history-003",
      reason: "IP относится к офисному VPN и совпадает с графиком смены.",
      session_id: "session-003",
    },
  ],
};

export const settingsWorkspace: SettingsWorkspace = {
  alert_rules: [
    {
      channel: "Slack #revenue",
      id: "alert-001",
      name: "Аномалия оттока",
      owner: "Аналитика",
      status: "active",
      threshold: "5.5%",
    },
    {
      channel: "Email финансы",
      id: "alert-002",
      name: "Падение MRR",
      owner: "Финансы",
      status: "active",
      threshold: "3.0%",
    },
    {
      channel: "Telegram поддержка",
      id: "alert-003",
      name: "Ошибки платежей",
      owner: "Поддержка",
      status: "review",
      threshold: "120/hour",
    },
  ],
  config_drafts: [
    {
      environment: "Продакшен",
      id: "draft-001",
      owner: "Администратор",
      section: "Валюта отчётов",
      status: "published",
      value: "RUB",
    },
    {
      environment: "Продакшен",
      id: "draft-002",
      owner: "Поддержка",
      section: "SLA поддержки",
      status: "review",
      value: "8 ч.",
    },
    {
      environment: "Стейджинг",
      id: "draft-003",
      owner: "Интеграции",
      section: "Повтор webhook",
      status: "draft",
      value: "3 попытки",
    },
  ],
  integrations: [
    {
      description: "Платежи и webhook для международных тарифов.",
      id: "stripe",
      latency: "180 ms",
      mode: "тест",
      name: "Stripe",
      status: "review",
    },
    {
      description: "Платежи в рублях и сверка подписок.",
      id: "robokassa",
      latency: "240 ms",
      mode: "боевой",
      name: "Robokassa",
      status: "healthy",
    },
    {
      description: "Операционные уведомления для процессов поддержки.",
      id: "telegram",
      latency: "90 ms",
      mode: "боевой",
      name: "Telegram",
      status: "healthy",
    },
    {
      description: "Отзывы iOS и события жизненного цикла подписок.",
      id: "app-store",
      latency: "синхр. 15 мин",
      mode: "боевой",
      name: "App Store",
      status: "disabled",
    },
  ],
  last_published_at: "12:40",
};

export const users: UserProfile[] = [
  {
    active_subscriptions: [
      {
        auto_renew: true,
        currency: "RUB",
        expires_at: "2026-06-18T21:00:00.000Z",
        id: "sub_anna_netflix",
        price: 1190,
        service: services.netflix,
        started_at: "2025-12-18T21:00:00.000Z",
        status: "active",
        tariff: "Ultimate",
        tariff_id: "tariff_ultimate",
      },
    ],
    avatar_url: null,
    block_reason: undefined,
    churn_probability: 0.18,
    churn_risk: "low",
    country: "Россия",
    devices: [
      {
        app_version: "2.8.1",
        id: "dev_anna_iphone",
        last_seen_at: "2026-05-19T14:12:00.000Z",
        model: "iPhone 15",
        platform: "ios",
      },
    ],
    email: "anna.morozova@example.com",
    id: "usr_anna_morozova",
    last_seen_at: "2026-05-19T14:12:00.000Z",
    mrr: 1190,
    name: "Анна Морозова",
    notes: [],
    phone: "+7 916 010-20-30",
    points_balance: 1540,
    registered_at: "2025-11-03T09:20:00.000Z",
    status: "active",
    subscriptions: [],
    tariff: "Ultimate",
    tariff_id: "tariff_ultimate",
  },
  {
    active_subscriptions: [
      {
        auto_renew: true,
        currency: "RUB",
        expires_at: "2026-05-25T21:00:00.000Z",
        id: "sub_ilya_yandex",
        price: 399,
        service: services.yandex,
        started_at: "2026-05-11T21:00:00.000Z",
        status: "active",
        tariff: "Plus",
        tariff_id: "tariff_plus",
      },
    ],
    avatar_url: null,
    block_reason: undefined,
    churn_probability: 0.72,
    churn_risk: "high",
    country: "Россия",
    devices: [
      {
        app_version: "2.8.0",
        id: "dev_ilya_pixel",
        last_seen_at: "2026-05-17T08:45:00.000Z",
        model: "Pixel 8",
        platform: "android",
      },
    ],
    email: "ilya.sokolov@example.com",
    id: "usr_ilya_sokolov",
    last_seen_at: "2026-05-17T08:45:00.000Z",
    mrr: 399,
    name: "Илья Соколов",
    notes: [],
    phone: "+7 921 111-22-33",
    points_balance: 260,
    registered_at: "2026-05-11T08:00:00.000Z",
    status: "trial",
    subscriptions: [],
    tariff: "Plus",
    tariff_id: "tariff_plus",
  },
  {
    active_subscriptions: [
      {
        auto_renew: true,
        currency: "RUB",
        expires_at: "2026-06-01T21:00:00.000Z",
        id: "sub_maria_family",
        price: 699,
        service: services.spotify,
        started_at: "2026-01-01T21:00:00.000Z",
        status: "active",
        tariff: "Family",
        tariff_id: "tariff_family",
      },
    ],
    avatar_url: null,
    churn_probability: 0.41,
    churn_risk: "medium",
    country: "Казахстан",
    devices: [
      {
        app_version: "2.7.9",
        id: "dev_maria_samsung",
        last_seen_at: "2026-05-18T19:30:00.000Z",
        model: "Samsung Galaxy S24",
        platform: "android",
      },
    ],
    email: "maria.volkova@example.com",
    id: "usr_maria_volkova",
    last_seen_at: "2026-05-18T19:30:00.000Z",
    mrr: 699,
    name: "Мария Волкова",
    notes: [],
    phone: null,
    points_balance: 810,
    registered_at: "2026-01-01T10:30:00.000Z",
    status: "active",
    subscriptions: [],
    tariff: "Family",
    tariff_id: "tariff_family",
  },
  {
    active_subscriptions: [],
    avatar_url: null,
    block_reason: "Chargeback abuse",
    churn_probability: 0.93,
    churn_risk: "high",
    country: "Россия",
    devices: [
      {
        app_version: "2.6.4",
        id: "dev_oleg_ipad",
        last_seen_at: "2026-04-29T12:00:00.000Z",
        model: "iPad Air",
        platform: "ios",
      },
    ],
    email: "oleg.petrov@example.com",
    id: "usr_oleg_petrov",
    last_seen_at: "2026-04-29T12:00:00.000Z",
    mrr: 0,
    name: "Олег Петров",
    notes: [],
    phone: "+7 999 000-11-22",
    points_balance: 0,
    registered_at: "2025-09-13T15:40:00.000Z",
    status: "blocked",
    subscriptions: [],
    tariff: "Legacy 2025",
    tariff_id: "tariff_legacy_2025",
  },
];

const userTextOverrides: Record<string, Pick<UserProfile, "country" | "name">> = {
  usr_anna_morozova: { country: "Россия", name: "Анна Морозова" },
  usr_ilya_sokolov: { country: "Россия", name: "Илья Соколов" },
  usr_maria_volkova: { country: "Казахстан", name: "Мария Волкова" },
  usr_oleg_petrov: { country: "Россия", name: "Олег Петров" },
};

users.forEach((user) => {
  const override = userTextOverrides[user.id];

  if (override) {
    user.country = override.country;
    user.name = override.name;
  }
});

users.forEach((user) => {
  user.subscriptions = user.active_subscriptions;
});
